name: github pages

on:
  push:
    branches:
      - main

jobs:
  check_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run code 
        run: make clean && make CFLAGS="-DUNIT_TEST" && ./wordle > CHECK.txt #Making one liner to compile and run code to output file

      - name: Check Output
        run: diff CHECK.txt test.txt